### PR TITLE
add further assertions into tests

### PR DESCRIPTION
**Pull request by seiyab**
Please merge this if you worry about existing functionality.

Derived from: #49

### NOTE
I had suggested following,
```js
const duration = array[array.length-1] - array[0]
ok(array.length <= duration / delay + 1)
```
but I found it is unsound because it has some errors (here "error" means difference between desired and actual measure, rather than [`Error`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)).

### CODE REVIEW

**Comment by niksy** [comment]
How will this help us with assertions in https://github.com/niksy/throttle-debounce/pull/49?

**Comment by seiyab** [comment]
This is not specific to https://github.com/niksy/throttle-debounce/pull/49.
It will prevent some regression checking execution interval.
The reason why I suggest it is that you have worry about changing the code.
Feel free to reject it if you don't feel it will help.

**Comment by niksy** [comment]
OK, let’s first finish up #49 and then we can see about adding additional assertions.

**Comment by seiyab** [comment]
I rebased latest master branch.

**Pull request closed without merging**
