### PR TITLE
Change browser from Chrome to ChromeHeadless

### PR DESCRIPTION
**Pull request by ossdev07**
**Changing the browser from Chrome to ChromeHeadless in karma.conf.js.**

As when using chromium binary to launch chrome then getting issues

~~~
15 10 2018 09:29:34.292:ERROR [launcher]: Cannot start Chrome

15 10 2018 09:29:34.292:ERROR [launcher]: Chrome stdout:
15 10 2018 09:29:34.292:ERROR [launcher]: Chrome stderr:
15 10 2018 09:29:34.298:INFO [launcher]: Trying to start Chrome again (1/2).
15 10 2018 09:29:35.145:ERROR [launcher]: Cannot start Chrome

15 10 2018 09:29:35.145:ERROR [launcher]: Chrome stdout:
15 10 2018 09:29:35.146:ERROR [launcher]: Chrome stderr:
15 10 2018 09:29:35.146:INFO [launcher]: Trying to start Chrome again (2/2).
15 10 2018 09:29:35.993:ERROR [launcher]: Cannot start Chrome

15 10 2018 09:29:35.994:ERROR [launcher]: Chrome stdout:
15 10 2018 09:29:35.994:ERROR [launcher]: Chrome stderr:
15 10 2018 09:29:35.995:ERROR [launcher]: Chrome failed 2 times (cannot start). Giving up.
~~~
But, if using chromeHeadless in place of Chrome then the browser launches

Headless browsers provide automated control of a web page in an environment similar to popular web browsers, but are executed via a command-line interface or using network communication

**Removed phantomjs dependency from package.json as phantomjs is an unmaintained project**.
Included " eslint-plugin-import " inside devdependencies as when using without it getting following issues

~~~
Oops! Something went wrong! :(

ESLint: 4.19.1.
ESLint couldn't find the plugin "eslint-plugin-import". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-import is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-import@latest --save-dev

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
~~~

Signed-off-by: ossdev <ossdev@puresoftware.com>

### CODE REVIEW

**Comment by ossdev07** [comment]
Ping @niksy 

Can you please have a look at this PR.
It will be a delight to have phantomjs removed from throttle-debounce.

**Comment by rhenwood-arm** [comment]
I would also like to see phantomjs removed. @niksy can you provide feedback on this PR?

**Comment by niksy** [comment]
@ossdev07 @rhenwood-arm hm, PhantomJS is development dependancy so I don’t see any problem here. Do you have problems on your development environments?

Tests don’t actually use PhantomJS so I can remove it and use Chrome. Headless Chrome isn’t really necessary since Travis provides good support for real Chrome.

**Comment by ossdev07** [comment]
You are right tests does not use phantomjs and it will be great if you can remove phantomjs from the development dependency as it is unmaintained now @niksy.

Please revert if you need me to do any modifications in this PR.

**Comment by ossdev07** [comment]
Thanks, for accepting this PR @niksy.

**Comment by ossdev07** [comment]
Hi @niksy 

On Second thoughts it will be better to use chrome headless instead of chrome, here are some of the benefits of using it:

- Headless browsers provide automated control of a web page in an environment similar to popular web browsers, but are executed via a command-line interface or using network communication.

- Also Headless Chrome is now shipped within Chrome for 10 versions (since 59, now 69).

- To provide multi-architecture support for the package it is better to use chrome headless since chrome does not work on aarch64 ( but chrome headless uses chromium which support both x86 and aarch64 ) and travis-ci uses x86 platform to run the test cases.

Using chrome headless instead of chrome will only add multi architecture support to the package hence it is a positive change.
Please do revert what are your thoughts on this also I will be happy to explain if you find anything not suitable or unclear.

**Comment by ossdev07** [comment]
Ping @niksy 

Sorry to bother you again, but could you please have a look at my suggestion of using chrome headless instead of chrome.
Please share your views on this.

**Comment by niksy** [comment]
@ossdev07 I still don’t understand why this is problem (regarding to my [comment](https://github.com/niksy/throttle-debounce/pull/24#issuecomment-450576695)). This is development dependancy and if you’re not working on developing this module, but just consuming it, this shouldn’t create problem for you. Or am I missing something?

**Comment by rhenwood-arm** [comment]
@niksy in my case, I would like to be able to develop on AArch64 - and PhantomJS is not available on that platform. I am also anticipating a CI loop, also on AArch64.

I think I understand that typically, even when developing an app using throttle-debounce, I may not need to run the test suite for throttle-debounce, but I would like to request this PR merged as a good hygiene update to remove an unmaintained package (and to enable the possibility of developing on aarch64 as well!)

**Comment by niksy** [comment]
@rhenwood-arm as I understand, your issue was with PhantomJS, not Chrome? PhantomJS is removed from the project.

**Comment by ossdev07** [comment]
@niksy Thanks for removing the PhantomJS, there is nothing else required to be done here.

**Comment by rhenwood-arm** [comment]
@niksy: seconded!

**Pull request merged**
