### PR TITLE
Delete index.d.ts

### PR DESCRIPTION
**Pull request by plee-nm**
Remove incorrect typings.

### CODE REVIEW

**Comment by franklixuefei** [comment]
Why? What's wrong?

**Review by franklixuefei — CHANGES_REQUESTED** [review]
why? this makes no sense.

**Comment by plee-nm** [comment]
@franklixuefei https://github.com/niksy/throttle-debounce/issues/14#issuecomment-396849758 No kidding.

**Comment by franklixuefei** [comment]
@niksy Please approve this PR since we already have one under @types

**Comment by franklixuefei** [comment]
@niksy Please approve this CR. Thank you.

**Review by franklixuefei — APPROVED** [review]

**Pull request merged**
