### PR TITLE
Allowed setTimeout and Date.now to be passed to throttle

### LINKED ISSUE #17: Allow injecting a custom setTimeout?
Hardcoding this to always use the global `setTimeout` is problematic. In most unit testing frameworks, there's no way to programmatically skip forward to the execution time - we'd have to also `setTimeout` in the tests.

Proposal: allow the methods to take in an object containing the settings, as it's starting to accept quite a few. What if we want to specify `noTrailing` and `setTimeout` but not `debounceMode`?

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
If immediate is a non-null object, it's used as a settings object that can provide a `scheduler` (defaulted to `setTimeout`) and `getTimestamp` (defaulted to `Number(new Date())`).

Note: this is technically a breaking change, as a non-boolean truthy `debounceMode` used to count as a boolean.

Fixes #17.

### CODE REVIEW

**Comment by niksy** [comment]
I don’t know if this should be implemented as major version. Seems too little changes for something like that. Maybe fifth parameter?

**Comment by JoshuaKGoldberg** [comment]
@niksy My two cents: it's hard to allow the user to provide many different forms of optional parameters with a linear list of them. For example, what if we want to pass `debounceMode` and `getTimestamp`, but not `scheduler`? How about only `scheduler`?

Re keeping to a minor version - sure. What would you prefer I do here? I'm ok with making more `package.json` changes or wouldn't be offended at all if you did them 😉.

**Comment by niksy** [comment]
@JoshuaKGoldberg yeah, I’m more of "3 parameters and no more" person so even original implementation isn’t my choice but it’s there to keep original implementation.

The original issue mentions unit testing functionality. What about mocking this module to avoid using `setTimeout`?

**Comment by JoshuaKGoldberg** [comment]
> mocking this module

Sure, though I'm personally a little against using module mocks as the primary form of stubbing out functionality in tests for a couple reasons:

* It makes tests' infrastructure (setup/teardown) rely on the implementation details of the code they're testing.
* It's dependent on the implementation details of the module but doesn't play well with static analysis (e.g. TypeScript) - if an API changes, module mocks may fail mysteriously.

Edit: undid any `package.json` changes

**Comment by niksy** [comment]
@JoshuaKGoldberg can you please review your changes so we can work more on this? I’ve thought about this and it seems that we can implement boolean/object behavior; this is similar to how [third argument in `addEventListener`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Syntax) works, so we’re somewhat aligned with the platform :).

**Comment by JoshuaKGoldberg** [comment]
I no longer use this library and don't want to spend the time working on it. All you! 🤷‍♂️

**Pull request closed without merging**
