### PR TITLE
[feature] add cancel for debounce

### PR DESCRIPTION
**Pull request by tedwu1027**
# description
* cancel for debounce and test-case 

No way to cancel #6

### CODE REVIEW

**Comment by niksy** [comment]
Hi @tedwu1027, can you please update README for this addition?

**Comment by CGNonofr** [comment]
This feature would be really nice, especially in a react project! Is there anything I can do to help?

**Comment by niksy** [comment]
@CGNonofr as mentioned in [my comment](https://github.com/niksy/throttle-debounce/pull/11#issuecomment-395703480), documentation for this feature would be great!

**Comment by CGNonofr** [comment]
https://github.com/niksy/throttle-debounce/pull/25

**Pull request merged**
