### PR TITLE
Added TypeScript types

### PR DESCRIPTION
**Pull request by a-korzun**

### CODE REVIEW

**Comment by cyberhck** [comment]
why is this not merged?

**Comment by niksy** [comment]
Hi @katasup @cyberhck, this has been merged to master and will be soon pushed as new version!

**Comment by davidspiess** [comment]
@niksy @katasup how about using generics to keep type safety in the callback function?

```ts
declare module "throttle-debounce" {
  type throttleFn = <T>(
    delay: number,
    noTrailing: boolean,
    callback?: T,
    debounceMode?: boolean
  ) => T;

  type debounceFn = <T>(
    delay: number,
    atBegin: boolean,
    callback?: T
  ) => T;

  const throttle: throttleFn;
  const debounce: debounceFn;
}
```

I think it would be better to incorporate the typings from `@types/throttle-debounce` as they support generics already.

**Comment by niksy** [comment]
@davidspiess I’m currently not that familiar with TypeScript so any improvements (and PR) to this are welcome 😄

**Comment by davidspiess** [comment]
@niksy if that's the case i would suggest you to remove the typings here and let the TS community handle them on their own on `definitelytyped.org`. So you don't have to worry about something you're not familiar with 😉

**Pull request merged**
