### PR TITLE
fix BABEL_ENV in Win10, travis ci fail fix.

### PR DESCRIPTION
**Pull request by billfeller**
fix: 
1. No files matching the pattern "'{index,lib/**/*,test/**/*}.js'" were found.
2. use cross-env BABEL_ENV instead.
3. travis build fail fix.

### CODE REVIEW

**Comment by niksy** [comment]
I understand the issue, but tests aren’t run in Windows 10 in CI, so this isn’t needed. Do you have specific case this change will fix?

**Comment by billfeller** [comment]
> I understand the issue, but tests aren’t run in Windows 10 in CI, so this isn’t needed. Do you have specific case this change will fix?

yeah, the cross-env is optional. i mean .travsi.yml `sh -e /etc/init.d/xvfb start` run fail just as https://travis-ci.org/billfeller/throttle-debounce/jobs/577223218.

there is 3 questions to fix.
1. use cross-env to run `npm run test:automated:local` successfully on window, linux, mac;
2. `update .travis.yml to fix ci fail` https://travis-ci.org/billfeller/throttle-debounce/jobs/577223218;
3. fix `npm run lint` running on window, linux, mac;

**Comment by billfeller** [comment]
image

**Comment by billfeller** [comment]
image

**Comment by niksy** [comment]
Tests are now executed inside Browserstack instances so this is not applicable anymore. If you still have issue with this, please open new issue.

**Pull request closed without merging**
